[server]
host = "localhost"
port = 40500
http-port = 40502
metrics-port = 40503
no-upnp = true
default-timeout = 2000
#bootstrap = "rnode://de6eed5d00cf080fc587eeb412cb31a75fd10358@52.119.8.109:40400"
standalone = false
data-dir = "~/rchain/node0"
map-size = 1073741824
casper-block-store-size = 1073741824
in-memory-store = false
max-num-of-connections = 500
[grpc-server]
host = "localhost"
port = 40501
port-internal = 40504
[tls]
#certificate = "/var/lib/rnode/certificate.pem"
#key = "/var/lib/rnode/key.pem"
[validators]
count = 5
shard-id = "rchain"
sig-algorithm = "ed25519"
#bonds-file = "./genesis/bonds.txt"
# wallets-file = ""
# known = ""
# public-key = "" # Inferred from private key
# WARNING!! Do not commit REAL private keys EVER. We'll stop doing this when it becomes practicable.
private-key = "6807fcdcb98249bbbe98dec53b4d242a3ae38f16f53f45c2b73a695723eb8f99"
# For sk files
# filename -> public key
# contents -> secret key